// [test] Guard memory-contract source citations, tool counts and bead-id-free prose
// against silent rot (my-beads-db-qy8.10.2)
//
// This test guards against three classes of silent drift that have recurred
// (and that an earlier version of this very guard failed to actually catch --
// see the per-guard design notes below for what changed and why):
//
// 1. Citation rot: every file:line citation under taxonomy.json's
//    groups[].codes[].source resolves to the construct it claims. Resolution
//    is TOKEN-based: each citation is checked against an explicit, hand
//    verified expected substring (not a generic "is the line non-blank"
//    check, which cannot tell a correct citation from one that drifted a few
//    lines into unrelated code -- that was GUARD 1's bug before this rewrite).
//
//    SCOPE: only groups[].codes[].source citations are checked. taxonomy.json
//    also carries file references in non_error_outcomes[].where and
//    excluded_from_closed_set.codes[].where, but those use a different field
//    shape (some name files with no line number at all, e.g.
//    N-ANCHOR-VERBATIM-MISSING) and were not part of what this lane's citation
//    refresh (my-beads-db-qy8.10.1) or the reviewer's falsifiability probes
//    touched. Narrowing to groups[].codes[].source keeps every citation this
//    guard checks backed by a verified, explicit token.
//
// 2. Count drift: live prose about the kb_*/code_* tool count must be
//    self-consistent with the REAL registered count, read directly off
//    src/services/tool-registry.ts (the actual registry, not another copy of
//    the prose -- generate-contract.mjs's KB_MODULES/CODE_EXPORTS lists were
//    the previous guard's source and that is exactly how it validated prose
//    against prose instead of against the registry).
//
// 3. Bead ids in shipped prose: contract artifacts under memory-contract/v1
//    must not contain tracker bead IDs outside code comments. This guard
//    scans the WHOLE memory-contract/v1 tree (a directory walk, not a
//    hardcoded file list -- the earlier version's hardcoded 7-file list is
//    why README.md and INVARIANTS-UNHOMED-DRAFT.md went unpoliced) and
//    matches both tracker id families seen in this repo's history
//    (`my-beads-db-...` and the hash-like `apra-fleet-...` shape named in
//    CLAUDE.md), while not false-positiving on ordinary compound names like
//    `apra-fleet-client`/`apra-fleet-workflow` (those carry no digit in the
//    segment right after the dash; real ids do -- 23c, b4g.4, 0cd.14, ...).
//
// EXCLUSIONS: The following are deliberately point-in-time transcripts and are
// skipped BY NAME (visible here, not implied by a path convention):
// - memory-contract/v1/SIGNOFF.md (final audit snapshot)
// - memory-contract/v1/tests/DRIFT-GUARD-DRYRUN.md (example output)
// - memory-contract/v1/T2A-COMPLETION-REPORT.md (final report)
//
// INVENTORY.md carries two DELIBERATE historical sentences (section 1 and
// section 6) stating the original pre-kb_demote count was 23 (16 kb_* + 7
// code_*) -- that is correct history, not drift, and is allow-listed by exact
// sentence text below (an anchored, justified exception, per the lane's
// re-planning correction) rather than by excluding the whole file, which
// would also blind GUARD 3 on the very file the bead-id rule most needs to
// police.
//
// docs/sprint-analysis-*.md files are per-sprint, hash-suffixed historical
// snapshots generated by the harvester after a sprint closes (see CLAUDE.md's
// "pre-computed cost analysis block"); they are never revisited once written,
// the same deliberate-transcript shape as the three named exclusions above,
// so they are skipped by filename pattern rather than enumerated individually.

import { readFileSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';

const REPO_ROOT = fileURLToPath(new URL('..', import.meta.url));
const MEMORY_CONTRACT_DIR = path.join(REPO_ROOT, 'memory-contract', 'v1');
const DOCS_DIR = path.join(REPO_ROOT, 'docs');

// ---------------------------------------------------------------------------
// Shared: recursive file walk, relative-path based (stable across OSes).
// ---------------------------------------------------------------------------

function walkFiles(baseDir: string): string[] {
  const out: string[] = [];
  const recurse = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        recurse(full);
      } else if (entry.isFile()) {
        out.push(path.relative(baseDir, full));
      }
    }
  };
  recurse(baseDir);
  return out;
}

// ===========================================================================
// GUARD 1: citation rot -- taxonomy.json groups[].codes[].source
// ===========================================================================

interface TaxonomyDoc {
  groups: Record<string, { codes: Array<{ code: string; source?: string }> }>;
}

interface Citation {
  file: string;
  startLine: number;
  endLine: number;
}

/**
 * Parse every file:line (and file:line-line) sub-citation out of a taxonomy
 * "source" string, handling the two multi-citation shapes actually used in
 * taxonomy.json:
 *  - continuations that omit the file ("sqlite-provider.ts:1545 (promote),
 *    :1744 (feedback)") -- inherit the most recently seen file;
 *  - a parenthetical annotation that itself may contain one nested paren pair
 *    and commas ("(assertCheckableBasis, KbCaptureRejected('x'))") -- must
 *    NOT be mistaken for a citation separator.
 *
 * Previous bug (pre-rewrite): the old regex required a bare `<name>.ts`
 * immediately before every colon, so continuation citations without a
 * restated filename were silently dropped (never checked), and it had no
 * paren-awareness at all.
 */
// A couple of taxonomy.json citations name a file WITHOUT its directory
// (e.g. "...at sqlite-provider.ts:1683" rather than the full
// "src/services/knowledge/sqlite-provider.ts:1683" every other citation of
// the same file uses). Canonicalized here rather than in taxonomy.json --
// that bare form was already verified correct by the citation refresh pass
// (my-beads-db-qy8.10.1) and is not part of what this guard was asked to
// rewrite.
const FILE_ALIASES: Record<string, string> = {
  'sqlite-provider.ts': 'src/services/knowledge/sqlite-provider.ts',
};

function extractCitations(source: string): Citation[] {
  const citations: Citation[] = [];
  let currentFile: string | undefined;
  const re = /([\w./-]+\.ts)?:(\d+)(?:-(\d+))?(?:\s*\(((?:[^()]|\([^()]*\))*)\))?/g;
  for (const m of source.matchAll(re)) {
    const [, file, startStr, endStr] = m;
    if (file) currentFile = file.includes('/') ? file : (FILE_ALIASES[file] ?? file);
    if (!currentFile) continue; // defensive; every real citation has a file eventually
    const startLine = parseInt(startStr, 10);
    const endLine = endStr ? parseInt(endStr, 10) : startLine;
    citations.push({ file: currentFile, startLine, endLine });
  }
  return citations;
}

/**
 * Expected token per citation location, keyed by "file:startLine". Each entry
 * was verified by hand against the working tree at authoring time (see
 * my-beads-db-qy8.10.1's commit): the exact substring that appears on the
 * cited line (or somewhere within the cited range) and uniquely identifies
 * the construct the taxonomy entry claims. A citation that drifts even a few
 * lines will, in every case checked here, land on a neighboring line that
 * does NOT carry this token (verified directly below for the two cases the
 * previous guard's own reviewer probe exploited).
 */
const EXPECTED_TOKENS: Record<string, string> = {
  'src/tools/kb-query.ts:55': 'Provide query',
  'src/services/knowledge/path-validation.ts:6': 'absolute',
  'src/services/knowledge/path-validation.ts:10': 'Path traversal rejected',
  'src/services/knowledge/sqlite-provider.ts:1683': 'validateFilePaths',
  'src/tools/kb-export.ts:159': 'repo_path does not exist',
  'src/tools/kb-import.ts:76': 'repo does not exist',
  'src/tools/kb-import.ts:144': 'bible file not found',
  'src/tools/kb-import.ts:151': 'bible file is not valid JSON',
  'src/tools/kb-import.ts:169': 'bible file is not a JSON array',
  'src/services/knowledge/sqlite-provider.ts:388': 'assertCheckableBasis',
  'src/services/knowledge/sqlite-provider.ts:394': 'no_source_files',
  'src/services/knowledge/sqlite-provider.ts:348': 'unresolvableBasisFiles',
  'src/services/knowledge/sqlite-provider.ts:404': 'missing_source_files',
  'src/tools/kb-import.ts:222': 'rejected',
  'src/services/knowledge/sqlite-provider.ts:1571': 'isNonTrivialPromoteReason',
  'src/services/knowledge/sqlite-provider.ts:1582': 'unresolvableBasisFiles',
  'src/services/knowledge/sqlite-provider.ts:1548': 'Cannot promote superseded',
  'src/services/knowledge/sqlite-provider.ts:1669': 'isNonTrivialPromoteReason',
  'src/services/knowledge/sqlite-provider.ts:1682': 'unresolvedEvidence',
  'src/services/knowledge/sqlite-provider.ts:1654': 'Cannot demote superseded',
  'src/services/knowledge/sqlite-provider.ts:1558': 'Cannot promote a user-directive',
  'src/services/knowledge/sqlite-provider.ts:1661': 'Cannot demote a user-directive',
  'src/services/knowledge/sqlite-provider.ts:1883': 'never auto-resolved',
  'src/services/knowledge/audn.ts:145': 'input.supersedes',
  'src/services/knowledge/audn.ts:224': "CONFIRMED') continue",
  'src/services/knowledge/sqlite-provider.ts:1877': 'genuine contradiction pair',
  'src/services/knowledge/sqlite-provider.ts:1873': 'already superseded',
  'src/services/knowledge/sqlite-provider.ts:1545': 'Entry not found',
  'src/services/knowledge/sqlite-provider.ts:1744': 'Entry not found',
  'src/services/knowledge/sqlite-provider.ts:1651': 'Entry not found',
  'src/services/knowledge/sqlite-provider.ts:1867': 'do not exist',
  'src/services/knowledge/sqlite-provider.ts:248': 'not initialized',
  'src/tools/code-intelligence.ts:131': 'is not configured',
  'src/tools/code-intelligence.ts:151': 'is not configured',
};

/** Resolve a citation: file must exist, range in bounds, token present somewhere in range. */
function resolveCitation(cite: Citation, expectedToken: string): { ok: boolean; error?: string } {
  const fullPath = path.join(REPO_ROOT, cite.file);
  let content: string;
  try {
    content = readFileSync(fullPath, 'utf8');
  } catch {
    return { ok: false, error: `File not found: ${cite.file}` };
  }

  const lines = content.split('\n');
  if (cite.startLine - 1 >= lines.length || cite.startLine < 1) {
    return { ok: false, error: `Line ${cite.startLine} out of range (file has ${lines.length} lines)` };
  }

  for (let line = cite.startLine; line <= cite.endLine; line++) {
    const text = lines[line - 1];
    if (text !== undefined && text.includes(expectedToken)) {
      return { ok: true };
    }
  }
  return {
    ok: false,
    error: `Expected token ${JSON.stringify(expectedToken)} not found in ${cite.file}:${cite.startLine}${cite.endLine !== cite.startLine ? `-${cite.endLine}` : ''}`,
  };
}

function readJsonDoc(filename: string): unknown {
  return JSON.parse(readFileSync(path.join(MEMORY_CONTRACT_DIR, filename), 'utf8'));
}

describe('memory-contract rot guard: GUARD 1 -- citation rot', () => {
  it('every taxonomy.json groups[].codes[].source citation resolves to its expected token', () => {
    const taxonomy = readJsonDoc('taxonomy.json') as TaxonomyDoc;
    const errors: string[] = [];

    for (const [groupName, group] of Object.entries(taxonomy.groups)) {
      for (const code of group.codes) {
        if (!code.source) {
          errors.push(`${code.code}: no source citation`);
          continue;
        }
        const citations = extractCitations(code.source);
        if (citations.length === 0) {
          errors.push(`${code.code} (${groupName}): no citation could be parsed from "${code.source}"`);
          continue;
        }
        for (const cite of citations) {
          const key = `${cite.file}:${cite.startLine}`;
          const expectedToken = EXPECTED_TOKENS[key];
          if (expectedToken === undefined) {
            errors.push(
              `${code.code} (${groupName}): ${key} has no entry in EXPECTED_TOKENS -- ` +
              `add one (this guard refuses to pass a citation it has never actually checked)`,
            );
            continue;
          }
          const resolved = resolveCitation(cite, expectedToken);
          if (!resolved.ok) {
            errors.push(`${code.code} (${groupName}): ${key} -> ${resolved.error}`);
          }
        }
      }
    }

    if (errors.length > 0) {
      throw new Error(`Citation rot detected:\n${errors.join('\n')}`);
    }
  });

  // Falsifiability: directly reproduce the reviewer's probe (shifting
  // E-DEMOTE-SUPERSEDED's citation from :1654 to :1658 produced NO error
  // under the old guard) against the REAL on-disk file, with no mutation.
  it('resolveCitation fails when a real citation is shifted a few lines, and passes at the true location', () => {
    const real: Citation = { file: 'src/services/knowledge/sqlite-provider.ts', startLine: 1654, endLine: 1654 };
    expect(resolveCitation(real, 'Cannot demote superseded').ok).toBe(true);

    const shifted: Citation = { ...real, startLine: 1658, endLine: 1658 };
    const shiftedResult = resolveCitation(shifted, 'Cannot demote superseded');
    expect(shiftedResult.ok).toBe(false);
  });

  // Second falsifiability case, reproducing the E-NO-BASIS staleness class
  // this lane fixed (citation off by ~50 lines, landing inside an unrelated
  // method).
  it('resolveCitation fails when a citation drifts ~50 lines into an unrelated construct', () => {
    const real: Citation = { file: 'src/services/knowledge/sqlite-provider.ts', startLine: 394, endLine: 394 };
    expect(resolveCitation(real, 'no_source_files').ok).toBe(true);

    const driftedToOldStaleCitation: Citation = { ...real, startLine: 339, endLine: 339 };
    expect(resolveCitation(driftedToOldStaleCitation, 'no_source_files').ok).toBe(false);
  });

  it('extractCitations parses continuation citations (no restated filename) and paren-nested annotations', () => {
    const multi = extractCitations(
      "src/services/knowledge/sqlite-provider.ts:1545 (promote), :1744 (feedback), :1651 (demote)",
    );
    expect(multi).toEqual([
      { file: 'src/services/knowledge/sqlite-provider.ts', startLine: 1545, endLine: 1545 },
      { file: 'src/services/knowledge/sqlite-provider.ts', startLine: 1744, endLine: 1744 },
      { file: 'src/services/knowledge/sqlite-provider.ts', startLine: 1651, endLine: 1651 },
    ]);

    const nestedParenAnnotation = extractCitations(
      "src/services/knowledge/sqlite-provider.ts:348 (unresolvableBasisFiles), :404 (assertCheckableBasis, KbCaptureRejected('missing_source_files'))",
    );
    expect(nestedParenAnnotation).toEqual([
      { file: 'src/services/knowledge/sqlite-provider.ts', startLine: 348, endLine: 348 },
      { file: 'src/services/knowledge/sqlite-provider.ts', startLine: 404, endLine: 404 },
    ]);

    const crossFileWithSemicolon = extractCitations(
      'src/services/knowledge/path-validation.ts:6 (absolute), :10 (traversal); demote evidence_files check at sqlite-provider.ts:1683',
    );
    expect(crossFileWithSemicolon).toEqual([
      { file: 'src/services/knowledge/path-validation.ts', startLine: 6, endLine: 6 },
      { file: 'src/services/knowledge/path-validation.ts', startLine: 10, endLine: 10 },
      { file: 'src/services/knowledge/sqlite-provider.ts', startLine: 1683, endLine: 1683 },
    ]);
  });
});

// ===========================================================================
// GUARD 2: tool-count drift
// ===========================================================================

/**
 * The actual registered tool count, read directly from the registry function
 * (NOT from generate-contract.mjs's KB_MODULES/CODE_EXPORTS -- that was the
 * previous guard's source, which validates one copy of the prose against
 * another copy of the prose, never against the real registration surface).
 */
function getRegisteredToolCounts(): { kb: number; code: number; total: number } {
  const registryContent = readFileSync(path.join(REPO_ROOT, 'src', 'services', 'tool-registry.ts'), 'utf8');
  const names = new Set<string>();
  for (const m of registryContent.matchAll(/server\.tool\('([a-z_]+)'/g)) {
    names.add(m[1]);
  }
  let kb = 0;
  let code = 0;
  for (const name of names) {
    if (name.startsWith('kb_')) kb++;
    else if (name.startsWith('code_')) code++;
  }
  return { kb, code, total: kb + code };
}

// Patterns describing the SUPERSEDED counts (pre-kb_demote: 23 tools = 16
// kb_* + 7 code_*). Deliberately specific (requires "tool"/"kb_" immediately
// after the number, optionally through a hyphen/backtick) rather than a bare
// \b23\b, which would false-positive on unrelated numbers (e.g. INVENTORY.md's
// own table row "23 | `code_flow` | ...").
const OLD_COUNT_PATTERNS: RegExp[] = [
  /\b23[\s-]*`?(?:tools?|kb_)/i,
  /\b16[\s-]*`?kb_/i,
  /\b15\s+of\s+the\s+16\b/i,
];

// Anchored, justified exceptions: exact historical sentences in INVENTORY.md
// that correctly describe the PRE-kb_demote audit and must not be deleted.
// Redacted (same-length, so line numbers in error messages stay accurate)
// before the pattern scan runs, rather than excluding the whole file -- this
// is also the only file GUARD 3 (bead ids) must still police after section 6.
const INVENTORY_HISTORICAL_ALLOWANCES: string[] = [
  'the verified number then was 23 (16 `kb_*` + 7 `code_*`).',
  '23-tool audit and the subsequent growth to 24; anything citing 23 today is',
];

const EXCLUDED_TRANSCRIPTS = new Set<string>([
  'SIGNOFF.md',
  path.join('tests', 'DRIFT-GUARD-DRYRUN.md'),
  'T2A-COMPLETION-REPORT.md',
]);

function redactAllowances(relPath: string, content: string): string {
  if (relPath !== 'INVENTORY.md') return content;
  let redacted = content;
  for (const allowed of INVENTORY_HISTORICAL_ALLOWANCES) {
    redacted = redacted.split(allowed).join(' '.repeat(allowed.length));
  }
  return redacted;
}

function findOldCountHits(relPath: string, content: string): string[] {
  const scanContent = redactAllowances(relPath, content);
  const hits: string[] = [];
  scanContent.split('\n').forEach((line, idx) => {
    if (OLD_COUNT_PATTERNS.some((p) => p.test(line))) {
      hits.push(`${relPath}:${idx + 1}: ${line.trim().slice(0, 160)}`);
    }
  });
  return hits;
}

describe('memory-contract rot guard: GUARD 2 -- tool-count drift', () => {
  it('matches the live registry: 17 kb_* + 7 code_* = 24', () => {
    const counts = getRegisteredToolCounts();
    expect(counts.kb).toBe(17);
    expect(counts.code).toBe(7);
    expect(counts.total).toBe(24);
  });

  it('no live memory-contract/v1 or docs/ file states a stale tool count', () => {
    const errors: string[] = [];

    for (const relPath of walkFiles(MEMORY_CONTRACT_DIR)) {
      if (EXCLUDED_TRANSCRIPTS.has(relPath)) continue;
      if (!/\.(md|mjs|json)$/.test(relPath)) continue;
      const content = readFileSync(path.join(MEMORY_CONTRACT_DIR, relPath), 'utf8');
      errors.push(...findOldCountHits(relPath, content));
    }

    for (const relPath of walkFiles(DOCS_DIR)) {
      if (!relPath.endsWith('.md')) continue;
      if (/^sprint-analysis-.*\.md$/.test(path.basename(relPath))) continue; // dated harvester snapshot
      const content = readFileSync(path.join(DOCS_DIR, relPath), 'utf8');
      errors.push(...findOldCountHits(relPath, content));
    }

    if (errors.length > 0) {
      throw new Error(`Tool-count drift detected:\n${errors.join('\n')}`);
    }
  });

  it('INVENTORY.md section 6 passes with its historical 23-tool sentence unedited, and still fails on a NEW 23-tool claim elsewhere in that file', () => {
    const realContent = readFileSync(path.join(MEMORY_CONTRACT_DIR, 'INVENTORY.md'), 'utf8');
    expect(findOldCountHits('INVENTORY.md', realContent)).toEqual([]);

    const withNewDrift = realContent + '\n\nThis document covers the 23-tool surface.\n';
    const hits = findOldCountHits('INVENTORY.md', withNewDrift);
    expect(hits.length).toBeGreaterThan(0);
    expect(hits[0]).toMatch(/23-tool surface/);
  });

  it('reintroducing a 23-tool or 16 kb_ string into a live, non-excluded file is caught', () => {
    expect(findOldCountHits('generate-contract.mjs', 'Same 23-tool roster as before.')).toHaveLength(1);
    expect(findOldCountHits('generate-contract.mjs', 'Still the 16 `kb_*` tools.')).toHaveLength(1);
    expect(findOldCountHits('generate-contract.mjs', '24 tools: 17 kb_* + 7 code_*, unchanged.')).toHaveLength(0);
  });
});

// ===========================================================================
// GUARD 3: bead ids in shipped memory-contract/v1 prose
// ===========================================================================

// Two tracker-id families seen in this repo's history:
//  - my-beads-db-XXX(.N)*  -- this clone's local bd database name, unambiguous.
//  - apra-fleet-XXX(.N)*   -- the convention named in CLAUDE.md. Restricted to
//    a short (2-6 char) first segment containing at least one digit, so it
//    matches real ids (23c, b4g.4, 0cd.14) without false-positiving on
//    ordinary compound package/product names that happen to follow
//    "apra-fleet-" (apra-fleet-client, apra-fleet-workflow, apra-fleet-se,
//    apra-fleet-src -- all pure-alpha, none contain a digit).
const BEAD_ID_PATTERN = /\bmy-beads-db-[a-zA-Z0-9]+(?:\.[0-9]+)*\b|\bapra-fleet-(?=[a-z0-9]{2,6}\b)[a-z]*[0-9][a-z0-9]*(?:\.[0-9]+)*\b/g;

function isCommentOrDescribeLine(relPath: string, line: string): boolean {
  if (!/\.(mjs|ts|js)$/.test(relPath)) return false; // .md/.json have no comment concept
  const trimmed = line.trim();
  return (
    trimmed.startsWith('//') ||
    trimmed.startsWith('*') ||
    trimmed.startsWith('/*') ||
    /^(describe|it|test)\(/.test(trimmed)
  );
}

describe('memory-contract rot guard: GUARD 3 -- bead ids in shipped prose', () => {
  it('no memory-contract/v1 artifact contains a tracker bead id outside code comments', () => {
    const errors: string[] = [];

    for (const relPath of walkFiles(MEMORY_CONTRACT_DIR)) {
      if (EXCLUDED_TRANSCRIPTS.has(relPath)) continue;

      const fullPath = path.join(MEMORY_CONTRACT_DIR, relPath);
      if (!statSync(fullPath).isFile()) continue;

      let content: string;
      try {
        content = readFileSync(fullPath, 'utf8');
      } catch {
        continue; // unreadable/binary; nothing to scan
      }

      content.split('\n').forEach((line, idx) => {
        if (!BEAD_ID_PATTERN.test(line)) {
          BEAD_ID_PATTERN.lastIndex = 0;
          return;
        }
        BEAD_ID_PATTERN.lastIndex = 0;
        if (isCommentOrDescribeLine(relPath, line)) return;
        errors.push(`${relPath}:${idx + 1}: ${line.trim().slice(0, 160)}`);
      });
    }

    if (errors.length > 0) {
      throw new Error(`Bead IDs in shipped memory-contract/v1 prose:\n${errors.join('\n')}`);
    }
  });

  it('reintroducing a tracker bead id into INVENTORY.md prose (anywhere, including past section 6) is caught', () => {
    const real = readFileSync(path.join(MEMORY_CONTRACT_DIR, 'INVENTORY.md'), 'utf8');

    const beforeSection6 = real.replace(
      '## 1. Verified tool count',
      'my-beads-db-zzz.1 landed this. ## 1. Verified tool count',
    );
    expect(beforeSection6).toMatch(BEAD_ID_PATTERN);

    const afterSection6 = real + '\n\nSee my-beads-db-zzz.2 for details.\n';
    expect(afterSection6).toMatch(BEAD_ID_PATTERN);

    // Both must actually be flagged by the same code path the real guard
    // uses, not merely matched by the raw regex above -- prove the fix for
    // the previous guard's "only scans substring(0, indexOf(section 6))"
    // bug, which made injections AFTER section 6 invisible.
    const flagLines = (content: string): string[] =>
      content.split('\n').filter((line) => {
        const hit = BEAD_ID_PATTERN.test(line);
        BEAD_ID_PATTERN.lastIndex = 0;
        return hit && !isCommentOrDescribeLine('INVENTORY.md', line);
      });
    expect(flagLines(beforeSection6).length).toBeGreaterThan(0);
    expect(flagLines(afterSection6).length).toBeGreaterThan(0);
  });

  it('the apra-fleet- id pattern matches real hash-like ids but not ordinary compound names', () => {
    expect('apra-fleet-23c').toMatch(BEAD_ID_PATTERN);
    expect('apra-fleet-b4g.4'.match(BEAD_ID_PATTERN)?.[0]).toBe('apra-fleet-b4g.4');
    BEAD_ID_PATTERN.lastIndex = 0;
    expect('apra-fleet-client').not.toMatch(BEAD_ID_PATTERN);
    BEAD_ID_PATTERN.lastIndex = 0;
    expect('apra-fleet-src input-name trap').not.toMatch(BEAD_ID_PATTERN);
    BEAD_ID_PATTERN.lastIndex = 0;
  });

  it('the three excluded transcripts are untouched and never scanned', () => {
    for (const relPath of EXCLUDED_TRANSCRIPTS) {
      const fullPath = path.join(MEMORY_CONTRACT_DIR, relPath);
      expect(() => readFileSync(fullPath, 'utf8')).not.toThrow();
      expect(walkFiles(MEMORY_CONTRACT_DIR).includes(relPath)).toBe(true); // sanity: file is really there
    }
    // The guard above explicitly `continue`s on these three paths; this test
    // just documents which three and that they still exist on disk.
  });
});
